config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories do
  	resources :chapters do
      collection do
      
      end
    end
  end
  

  get 'homepage/index'

  root 'homepage#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chapter.rb
class Chapter < ApplicationRecord
  belongs_to :story
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  has_many :chapters
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :find_story
  before_action :authenticate_user! , except: [:show]

  def index
  end

  def show

  	@chapter = @story.chapters.find(params[:id])
  end

  def new
  	
  end

  def create
    @chapter = @story.chapters.create(chapter_params)

    if @chapter.save
      redirect_to story_chapter_path(@story, @chapter.id)
    else
      render 'new'
    end
  end

  def edit

  	@chapter = @story.chapters.find(params[:id])
  end

  def update
  	@chapter = @story.chapters.find(params[:id])
  	if @chapter.update(chapter_params)
  	  redirect_to story_chapter_path(@story, @chapter.id)
  	else
  	  render 'edit'
  	end
  end
  
  def destroy
    @chapter = @story.chapters.find(params[:id])
    @chapter.destroy
    redirect_to story_path(@story)
  end
  private

    def find_story
    
      @story = Story.find(params[:story_id])
    end

    def chapter_params
      params.require(:chapter).permit(:name, :content)
    end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , except: [:index, :show]

  # GET /stories
  # GET /stories.json
  def index
    @stories = Story.all
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
   
  end

  # GET /stories/new
  def new
    @story = current_user.stories.build
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = current_user.stories.build(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:name, :description, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/chapters/_form.html.erb
<%= form_with(model: [ @story, @story.chapters.build ], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/chapters/edit.html.erb
<h2>Edit your chap:</h2>
<%= form_with(model: [ @story, @chapter], local: true) do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
  <p>
    <%= form.submit "Update" %>
  </p>
<% end %>

app/views/chapters/new.html.erb
<h2 style = "text-align: center; color: blue">Create new chap</h2>
<%= render 'chapters/form' %>

app/views/chapters/show.html.erb
<h2><%= @chapter.name %></h2>
<p><%= @chapter.content %></p>
<% if @story.user == current_user %>
  <%= link_to 'Edit', edit_story_chapter_path(@story, @chapter.id) %> 
  <%= link_to 'Destroy Chap', story_chapter_path(@story, @chapter.id),
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
<% end %>
<p>qerqe qerqwe adf qwer alkj;  pi pqj;lk p ; u p q;erj qe;rlq er; qlekjr; qlekjr ;qej;</p>
<%= link_to 'Back', story_path(@story) %>

app/views/homepage/index.html.erb
<h1>Welcom to my page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to image_tag("logo.jpeg", :class => "logo img-responsive"), stories_path, {:style =>'padding: 0'} %></li>
            <li class = "link"><%= link_to("The loai", "#") %></li>
          </ul>
          <% if user_signed_in? %>
            <h3><%= link_to('Logout', destroy_user_session_path, method: :delete) %></h3> 
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><%= link_to("Sign_in", new_user_session_path) %></li>
              <li><%= link_to("Sign_up", new_user_registration_path) %></li>
            </ul>
          <% end %>
          <form class="navbar-form navbar-right" role="search">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
          </form>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>

    <%= yield %>

  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story, local: true) do |form| %>
  <% if story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Author</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.name %></td>
        <td><%= story.description %></td>
        <td><%= story.author %></td>
        <td><%= link_to 'Show', story %></td>
        <% if story.user == current_user  %>
          <td><%= link_to 'Edit', edit_story_path(story) %></td>
          <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<% if user_signed_in?  %>
  <%= link_to 'New Story', new_story_path %>
<% end %>
<br>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form', story: @story %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<h2 style = "text-align: center; color: red">
  
  <%= @story.name %>
</h2>

<p style = "text-align: left">
 
  <%= @story.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @story.author %>
</p>

<% @story.chapters.each do |chap| %>
  <p><%= link_to chap.name, story_chapter_path(@story, chap.id) %></p>
<% end %>
<% if @story.user == current_user %>
  <%= link_to 'Add new chap', new_story_chapter_path(@story) %>
<% end %>
<br>
<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>